components:
  schemas:
    CategoryEntityReferences:
      description: DocRef(CategoryEntityReferencesDescription)
      type: object
      required:
        - categories
      properties:
        categories:
          type: array
          minItems: 1
          maxItems: 1024
          description: DocRef(CategoryListSpecDescription)
          items:
            type: string
            x-constraints:
              pattern: "ConstantRef({ext:common:/namespaces/common}, uuidPattern)"
      x-codegen-hint:
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: "categories"
                  index: 2001