components:
  schemas:
    ClusterProfile:
      x-filterable-properties:
        - name
        - clusterCount
        - driftedClusterCount
        - lastUpdateTime
        - createdBy
        - createTime
        - lastUpdatedBy
      x-sortable-properties:
        - name
        - clusterCount
        - driftedClusterCount
        - lastUpdateTime
        - createdBy
        - createTime
        - lastUpdatedBy
      x-property-mapping:
        - name: "name"
          value: "name"
        - name: "clusterCount"
          value: "attached_clusters_count"
        - name: "driftedClusterCount"
          value: "drifted_clusters_count"
        - name: "lastUpdateTime"
          value: "last_update_time.seconds"
        - name: "extId"
          value: "_entity_id_"
        - name: "createdBy"
          value: "created_by"
        - name: "createTime"
          value: "create_time.seconds"
        - name: "lastUpdatedBy"
          value: "last_updated_by"
      x-entity: cluster_profile
      x-rbac-entity: cluster_profile
      x-rbac-property-mapping:
        - name: "uuid"
          value: "extId"
        - name: "owner_uuid"
          value: "createdBy"
      allOf:
        - $ref: ModelRef({ext:common:/namespaces/common/versioned/v1/modules/response/beta/models/ExternalizableAbstractModel})
        - type: "object"
          required:
            - name
          description: DocRef(ClusterProfileEntityDesc)
          properties:
            name:
              description: DocRef(ClusterProfileNameDesc)
              type: "string"
              x-constraints:
                maxLength: ConstantRef(maxClusterProfileNameLength)
                pattern: ConstantRef(clusterProfileNamePattern)
            description:
              description: DocRef(ClusterProfileDescriptionDesc)
              type: "string"
              x-constraints:
                maxLength: ConstantRef(maxClusterProfileDescriptionNameLength)
            createTime:
              description: DocRef(ClusterProfileCreateTimeDesc)
              type: string
              format: date-time
              readOnly: true
            lastUpdateTime:
              description: DocRef(ClusterProfileUpdateTimeDesc)
              type: string
              format: date-time
              readOnly: true
            createdBy:
              description: DocRef(ClusterProfileCreatedByDesc)
              readOnly: true
              type: "string"
              x-constraints:
                pattern: "ConstantRef({ext:common:/namespaces/common}, uuidPattern)"
            lastUpdatedBy:
              description: DocRef(ClusterProfileLastUpdatedByDesc)
              readOnly: true
              type: "string"
              x-constraints:
                pattern: "ConstantRef({ext:common:/namespaces/common}, uuidPattern)"
            clusterCount:
              description: DocRef(ManagedClusterCountDesc)
              type: "integer"
              format: int32
              readOnly: true
            driftedClusterCount:
              description: DocRef(DriftedClusterCountDesc)
              type: "integer"
              format: int32
              readOnly: true
            clusters:
              description: DocRef(ManageClusterConfigDesc)
              readOnly: true
              type: array
              x-constraints:
                minItems: ConstantRef(minManagedClustersCount)
                maxItems: ConstantRef(maxManagedClustersCount)
              items:
                $ref: ModelRef({./ManagedCluster})
            allowedOverrides:
              description: DocRef(AllowOverrideDesc)
              type: array
              x-constraints:
                minItems: ConstantRef(minConfigCount)
                maxItems: ConstantRef(maxConfigCount)
              items:
                $ref: ModelRef({./ConfigType})
            nameServerIpList:
              description: DocRef(NameServerDesc)
              type: array
              x-constraints:
                minItems: ConstantRef(minNameServersCount)
                maxItems: ConstantRef(maxNameServersCount)
              items:
                $ref: ModelRef({ext:common:/namespaces/common/versioned/v1/modules/config/beta/models/IPAddress})
            ntpServerIpList:
              description: DocRef(NtpServerDesc)
              type: array
              x-constraints:
                minItems: ConstantRef(minNtpServersCount)
                maxItems: ConstantRef(maxNtpServersCount)
              items:
                $ref: ModelRef({ext:common:/namespaces/common/versioned/v1/modules/config/beta/models/IPAddressOrFQDN})
            smtpServer:
              description: DocRef(SmtpServerDesc)
              $ref: ModelRef({./SmtpServerRef})
            nfsSubnetWhitelist:
              description: DocRef(NfsSubnetWhitelistDesc)
              type: array
              x-constraints:
                minItems: ConstantRef(minNfsSubnetWhitelistCount)
                maxItems: ConstantRef(maxNfsSubnetWhitelistCount)
              items:
                type: "string"
                x-constraints:
                  pattern: ConstantRef(nfsSubnetWhitelistConstraint)
            snmpConfig:
              description: DocRef(SnmpInfo)
              $ref: ModelRef({./SnmpConfig})
            rsyslogServerList:
              description: DocRef(RsyslogServer)
              type: array
              x-constraints:
                minItems: ConstantRef(minRsyslogServersCount)
                maxItems: ConstantRef(maxRsyslogServersCount)
              items:
                $ref: ModelRef({./RsyslogServer})
            pulseStatus:
              description: DocRef(PulseStatusDesc)
              $ref: ModelRef({./PulseStatus})
      x-codegen-hint:
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - type: "ModelRef({ext:common:/namespaces/common/versioned/v1/modules/response/beta/models/ExternalizableAbstractModel})"
                  name: base
                  index: 2001
                - name: "name"
                  index: 2002
                - name: "description"
                  index: 2003
                - name: "createTime"
                  index: 2004
                - name: "lastUpdateTime"
                  index: 2005
                - name: "createdBy"
                  index: 2006
                - name: "lastUpdatedBy"
                  index: 2007
                - name: "clusterCount"
                  index: 2008
                - name: "driftedClusterCount"
                  index: 2009
                - name: "clusters"
                  index: 2010
                - name: "allowedOverrides"
                  index: 2011
                - name: "nameServerIpList"
                  index: 2012
                - name: "ntpServerIpList"
                  index: 2013
                - name: "smtpServer"
                  index: 2014
                - name: "nfsSubnetWhitelist"
                  index: 2015
                - name: "snmpConfig"
                  index: 2016
                - name: "rsyslogServerList"
                  index: 2017
                - name: "pulseStatus"
                  index: 2018

    ManagedCluster:
      x-complex-type-edm: true
      x-filterable-properties:
        - extId
        - isCompliant
      x-property-mapping:
        - name: "extId"
          value: "attached_cluster_uuids"
        - name: "isCompliant"
          value: "attached_cluster_compliant_status"
      type: "object"
      description: DocRef(ManageClusterConfigDesc)
      required:
        - extId
      properties:
        extId:
          description: DocRef(ClusterExtIdDescription)
          type: "string"
          x-constraints:
            pattern: "ConstantRef({ext:common:/namespaces/common}, uuidPattern)"
        isCompliant:
          description: DocRef(IsCompliantDesc)
          readOnly: true
          type: "boolean"
        lastSyncedTime:
          description: DocRef(ClusterProfileLastSyncedTimeDesc)
          readOnly: true
          type: string
          format: date-time
        configDrifts:
          description: DocRef(DriftedSettingsDesc)
          readOnly: true
          type: array
          x-constraints:
            minItems: ConstantRef(minConfigCount)
            maxItems: ConstantRef(maxConfigCount)
          items:
            $ref: ModelRef({./ConfigType})
      x-codegen-hint:
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: "extId"
                  index: 2001
                - name: "isCompliant"
                  index: 2002
                - name: "lastSyncedTime"
                  index: 2003
                - name: "configDrifts"
                  index: 2004

    ConfigType:
      allOf:
        - $ref: "ModelRef({ext:common:/namespaces/common/versioned/v1/modules/config/beta/models/BaseEnum})"
        - type: "string"
          enum:
            - NTP_SERVER_CONFIG
            - NAME_SERVER_CONFIG
            - SMTP_SERVER_CONFIG
            - NFS_SUBNET_WHITELIST_CONFIG
            - SNMP_SERVER_CONFIG
            - RSYSLOG_SERVER_CONFIG
            - PULSE_CONFIG
          x-codegen-hint:
            $any:
              - type: enum
                properties:
                  descriptions:
                    - name: 'NTP_SERVER_CONFIG'
                      description: DocRef(NtpServerSettingDesc)
                    - name: 'NAME_SERVER_CONFIG'
                      description: DocRef(NameServerSettingDesc)
                    - name: 'SMTP_SERVER_CONFIG'
                      description: DocRef(SmtpServerSettingDesc)
                    - name: 'NFS_SUBNET_WHITELIST_CONFIG'
                      description: DocRef(NfsSubnetWhitelistSettingDesc)
                    - name: 'SNMP_SERVER_CONFIG'
                      description: DocRef(SnmpServerSettingDesc)
                    - name: 'RSYSLOG_SERVER_CONFIG'
                      description: DocRef(RsyslogServerSettingDesc)
                    - name: 'PULSE_CONFIG'
                      description: DocRef(PulseStatusDesc)
              - type: entity-identifier
                properties:
                  identifiers:
                    - value: "NTP_SERVER_CONFIG"
                      index: 2001
                    - value: "NAME_SERVER_CONFIG"
                      index: 2002
                    - value: "SMTP_SERVER_CONFIG"
                      index: 2003
                    - value: "NFS_SUBNET_WHITELIST_CONFIG"
                      index: 2004
                    - value: "SNMP_SERVER_CONFIG"
                      index: 2005
                    - value: "RSYSLOG_SERVER_CONFIG"
                      index: 2006
                    - value: "PULSE_CONFIG"
                      index: 2007

    ClusterReferenceListSpec:
      type: "object"
      required:
        - clusters
      properties:
        clusters:
          description: DocRef(ClusterReferenceDesc)
          type: array
          x-constraints:
            minItems: ConstantRef(minManagedClustersCount)
            maxItems: ConstantRef(maxManagedClustersCount)
          items:
            $ref: ModelRef({./ClusterReference})
      x-codegen-hint:
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: "clusters"
                  index: 2001