components:
  schemas:
    PhysicalGpuConfig:
      x-complex-type-edm: true
      x-property-mapping:
        - name: "type"
          value: "gpu_type"
        - name: "mode"
          value: "gpu_mode"
        - name: "vendorName"
          value: "vendor_name"
        - name: "deviceId"
          value: "device_id"
        - name: "deviceName"
          value: "device_name"
        - name: "sbdf"
          value: "sbdf"
        - name: "inUse"
          value: "in_use"
        - name: "assignable"
          value: "assignable"
        - name: "numaNode"
          value: "numa_node"
        - name: "frameBufferSizeBytes"
          value: "frame_buffer_size_bytes"
      description: DocRef(PhysicalGpuConfigDesc)
      type: "object"
      properties:
        type:
          description: DocRef(GpuTypeDesc)
          $ref: ModelRef({./GpuType})
        deviceId:
          description: DocRef(DeviceIdDesc)
          type: "integer"
          format: int64
        deviceName:
          description: DocRef(DeviceNameDesc)
          type: "string"
        vendorName:
          description: DocRef(VendorNameDesc)
          type: "string"
        inUse:
          description: DocRef(GpuInUseDesc)
          type: "boolean"
        sbdf:
          description: DocRef(GpuSbdfDesc)
          type: "string"
        numaNode:
          description: DocRef(NumaNodeDesc)
          type: "string"
        assignable:
          description: DocRef(GpuAssignableDesc)
          type: "integer"
          format: int64
        mode:
          description: DocRef(GpuModeDesc)
          $ref: ModelRef({./GpuMode})
        frameBufferSizeBytes:
          description: DocRef(FrameBufferSizeBytesDesc)
          type: "integer"
          format: int64
      x-codegen-hint:
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: "type"
                  index: 2001
                - name: "deviceId"
                  index: 2002
                - name: "deviceName"
                  index: 2003
                - name: "vendorName"
                  index: 2004
                - name: "inUse"
                  index: 2005
                - name: "sbdf"
                  index: 2006
                - name: "numaNode"
                  index: 2007
                - name: "assignable"
                  index: 2008
                - name: "mode"
                  index: 2009
                - name: "frameBufferSizeBytes"
                  index: 2010

    VirtualGpuConfig:
      x-complex-type-edm: true
      x-property-mapping:
        - name: "type"
          value: "gpu_type"
        - name: "vendorName"
          value: "vendor_name"
        - name: "deviceId"
          value: "device_id"
        - name: "deviceName"
          value: "device_name"
        - name: "sbdf"
          value: "sbdf"
        - name: "inUse"
          value: "in_use"
        - name: "assignable"
          value: "assignable"
        - name: "licenses"
          value: "licenses"
        - name: "numaNode"
          value: "numa_node"
        - name: "guestDriverVersion"
          value: "guest_driver_version"
        - name: "fraction"
          value: "fraction"
        - name: "numberOfVirtualDisplayHeads"
          value: "num_virtual_display_heads"
        - name: "maxResolution"
          value: "max_resolution"
        - name: "frameBufferSizeBytes"
          value: "frame_buffer_size_bytes"
      description: DocRef(VirtualGpuConfigDesc)
      type: "object"
      properties:
        type:
          description: DocRef(GpuTypeDesc)
          $ref: ModelRef({./GpuType})
        deviceId:
          description: DocRef(DeviceIdDesc)
          type: "integer"
          format: int64
        deviceName:
          description: DocRef(DeviceNameDesc)
          type: "string"
        vendorName:
          description: DocRef(VendorNameDesc)
          type: "string"
        inUse:
          description: DocRef(GpuInUseDesc)
          type: "boolean"
        sbdf:
          description: DocRef(GpuSbdfDesc)
          type: "string"
        numaNode:
          description: DocRef(NumaNodeDesc)
          type: "string"
        assignable:
          description: DocRef(GpuAssignableDesc)
          type: "integer"
          format: int64
        fraction:
          description: DocRef(GpuFractionDesc)
          type: "integer"
          format: int64
        guestDriverVersion:
          description: DocRef(GuestDriverVersionDesc)
          type: "string"
        licenses:
          description: DocRef(GpuLicenseDesc)
          type: array
          x-constraints:
            minItems: 0
            maxItems: 1024
          items:
            type: "string"
        numberOfVirtualDisplayHeads:
          description: DocRef(NumberOfVirtualDisplayHeadsDesc)
          type: "integer"
          format: int64
        frameBufferSizeBytes:
          description: DocRef(FrameBufferSizeBytesDesc)
          type: "integer"
          format: int64
        maxResolution:
          description: DocRef(MaxResolutionDesc)
          type: "string"
      x-codegen-hint:
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: "type"
                  index: 2001
                - name: "deviceId"
                  index: 2002
                - name: "deviceName"
                  index: 2003
                - name: "vendorName"
                  index: 2004
                - name: "inUse"
                  index: 2005
                - name: "sbdf"
                  index: 2006
                - name: "numaNode"
                  index: 2007
                - name: "assignable"
                  index: 2008
                - name: "fraction"
                  index: 2009
                - name: "guestDriverVersion"
                  index: 2010
                - name: "licenses"
                  index: 2011
                - name: "numberOfVirtualDisplayHeads"
                  index: 2013
                - name: "frameBufferSizeBytes"
                  index: 2014
                - name: "maxResolution"
                  index: 2015
  
    GpuMode:
      description: DocRef(GpuModeDesc)
      allOf:
        - $ref: "ModelRef({ext:common:/namespaces/common/versioned/v1/modules/config/beta/models/BaseEnum})"
        - type: "string"
          enum:
            - UNUSED
            - USED_FOR_PASSTHROUGH
            - USED_FOR_VIRTUAL
          x-property-mapping:
            - name: UNUSED
              value: kUnused
            - name: USED_FOR_PASSTHROUGH
              value: kUsedForPassthrough
            - name: USED_FOR_VIRTUAL
              value: kUsedForVirtual
          x-codegen-hint:
            $any:
              - type: enum
                properties:
                  descriptions:
                    - name: 'UNUSED'
                      description: DocRef(UnusedModeDescription)
                    - name: 'USED_FOR_PASSTHROUGH'
                      description: DocRef(UsedPassThruModeDescription)
                    - name: 'USED_FOR_VIRTUAL'
                      description: DocRef(UsedVirtualModeDescription)
              - type: entity-identifier
                properties:
                  identifiers:
                    - value: "UNUSED"
                      index: 2001
                    - value: "USED_FOR_PASSTHROUGH"
                      index: 2002
                    - value: "USED_FOR_VIRTUAL"
                      index: 2003

    GpuType:
      description: DocRef(GpuTypeDesc)
      allOf:
        - $ref: "ModelRef({ext:common:/namespaces/common/versioned/v1/modules/config/beta/models/BaseEnum})"
        - type: "string"
          enum:
            - PASSTHROUGH_GRAPHICS
            - PASSTHROUGH_COMPUTE
            - VIRTUAL
          x-property-mapping:
            - name: PASSTHROUGH_GRAPHICS
              value: kPassthroughGraphics
            - name: PASSTHROUGH_COMPUTE
              value: kPassthroughCompute
            - name: VIRTUAL
              value: kVirtual
          x-codegen-hint:
            $any:
              - type: enum
                properties:
                  descriptions:
                    - name: 'PASSTHROUGH_GRAPHICS'
                      description: DocRef(PassThruGraphicsTypeDescription)
                    - name: 'PASSTHROUGH_COMPUTE'
                      description: DocRef(PassThruComputeTypeDescription)
                    - name: 'VIRTUAL'
                      description: DocRef(VirtualTypeDescription)
              - type: entity-identifier
                properties:
                  identifiers:
                    - value: "PASSTHROUGH_GRAPHICS"
                      index: 2001
                    - value: "PASSTHROUGH_COMPUTE"
                      index: 2002
                    - value: "VIRTUAL"
                      index: 2003

    PhysicalGpuProfile:
      description: DocRef(PhysicalGpuProfileDesc)
      allOf:
        - $ref: ModelRef({ext:common:/namespaces/common/versioned/v1/modules/response/beta/models/ExternalizableAbstractModel})
        - type: "object"
          properties:
            physicalGpuConfig:
              description: DocRef(PhysicalGpuConfigDesc)
              $ref: ModelRef({./PhysicalGpuConfig})
            allocatedVmExtIds:
              description: DocRef(AllocatedVmExtIdsDesc)
              type: array
              items:
                type: "string"
                x-constraints:
                  pattern: "ConstantRef({ext:common:/namespaces/common}, uuidPattern)"            
              x-constraints:
                minItems: 0
                maxItems: 1024
      x-codegen-hint:
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - type: "ModelRef({ext:common:/namespaces/common/versioned/v1/modules/response/beta/models/ExternalizableAbstractModel})"
                  name: base
                  index: 2001
                - name: "physicalGpuConfig"
                  index: 2002
                - name: "allocatedVmExtIds"
                  index: 2003

    VirtualGpuProfile:
      description: DocRef(VirtualGpuProfileDesc)
      allOf:
        - $ref: ModelRef({ext:common:/namespaces/common/versioned/v1/modules/response/beta/models/ExternalizableAbstractModel})
        - type: "object"
          properties:
            virtualGpuConfig:
              description: DocRef(VirtualGpuConfigDesc)
              $ref: ModelRef({./VirtualGpuConfig})
            allocatedVmExtIds:
              description: DocRef(AllocatedVmExtIdsDesc)
              type: array
              items:
                type: "string"
                x-constraints:
                  pattern: "ConstantRef({ext:common:/namespaces/common}, uuidPattern)"            
              x-constraints:
                minItems: 0
                maxItems: 1024
      x-codegen-hint:
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - type: "ModelRef({ext:common:/namespaces/common/versioned/v1/modules/response/beta/models/ExternalizableAbstractModel})"
                  name: base
                  index: 2001
                - name: "virtualGpuConfig"
                  index: 2002
                - name: "allocatedVmExtIds"
                  index: 2003
