components:
  schemas:
    NetworkSegment:
      allOf:
        - $ref: ModelRef({ext:common:/namespaces/common/versioned/v1/modules/response/beta/models/ExternalizableAbstractModel})
        - type: "object"
          description: DocRef(NetworkSegmentInfo)
          properties:
            name:
              description: DocRef(NetworkSegmentNameDesc)
              type: "string"
              x-constraints:
                maxLength: ConstantRef(maxNameLength)
            ipPool:
              description: DocRef(NsIpPoolDesc)
              type: "string"
              x-constraints:
                maxLength: ConstantRef(maxIpPoolNameLength)
            ipPoolType:
              description: DocRef(NsIpPoolTypeDesc)
              $ref: ModelRef({./NsIpPoolType})
            vlanId:
              description: DocRef(NsVlanIdDesc)
              type: "integer"
              format: int32
            subnet:
              description: DocRef(NsSubnetDesc)
              $ref: ModelRef({ext:common:/namespaces/common/versioned/v1/modules/config/beta/models/IPAddress})
            netmask:
              description: DocRef(NsNetmaskDesc)
              $ref: ModelRef({ext:common:/namespaces/common/versioned/v1/modules/config/beta/models/IPAddress})
            gateway:
              description: DocRef(NsGatewayDesc)
              $ref: ModelRef({ext:common:/namespaces/common/versioned/v1/modules/config/beta/models/IPAddress})
            priorityBasedFlowControl:
              description: DocRef(NsPfcDesc)
              type: "integer"
              format: int32
            isUseZeroTouchRoceEnabled:
              description: DocRef(UseZtrDesc)
              type: "boolean"
              default: false
            services:
              description: DocRef(NetworkSegmentServiceDesc)
              type: array
              minItems: 0
              maxItems: 4
              items:
                $ref: ModelRef({./NetworkSegmentService})
            vnic:
              description: DocRef(NetworkSegmentVnicInfoDesc)
              type: array
              minItems: 0
              maxItems: 64
              items:
                $ref: ModelRef({./NetworkSegmentVnicInfo})
            networkBacking:
              description: DocRef(NetworkSegmentNetworkBackingDesc)
              type: array
              minItems: 1
              maxItems: 2
              items:
                $ref: ModelRef({./NetworkSegmentNetworkBacking})
      x-filterable-properties:
        - name
        - services
      x-sortable-properties:
        - name
      x-property-mapping:
        - name: "name"
          value: "descriptive_name"
      x-internal: true
      x-codegen-hint:
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - type: "ModelRef({ext:common:/namespaces/common/versioned/v1/modules/response/beta/models/ExternalizableAbstractModel})"
                  name: base
                  index: 2001
                - name: "name"
                  index: 2002
                - name: "ipPool"
                  index: 2003
                - name: "ipPoolType"
                  index: 2004
                - name: "vlanId"
                  index: 2005
                - name: "subnet"
                  index: 2006
                - name: "netmask"
                  index: 2007
                - name: "gateway"
                  index: 2008
                - name: "priorityBasedFlowControl"
                  index: 2009
                - name: "isUseZeroTouchRoceEnabled"
                  index: 2010
                - name: "services"
                  index: 2011
                - name: "vnic"
                  index: 2012
                - name: "networkBacking"
                  index: 2013

    NetworkSegmentVnicInfo:
      description: DocRef(NetworkSegmentVnicInfoDesc)
      type: "object"
      properties:
        nodeUuid:
          description: DocRef(NodeUuid)
          type: "string"
          x-constraints:
            pattern: "ConstantRef({ext:common:/namespaces/common}, uuidPattern)"
        cvmInterfaceIp:
          description: DocRef(NsCvmInterfaceIp)
          $ref: ModelRef({ext:common:/namespaces/common/versioned/v1/modules/config/beta/models/IPAddress})
        hypervisorInterfaceIp:
          description: DocRef(NsHypervisorInterfaceIp)
          $ref: ModelRef({ext:common:/namespaces/common/versioned/v1/modules/config/beta/models/IPAddress})
      x-internal: true
      x-codegen-hint:
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: "nodeUuid"
                  index: 2001
                - name: "cvmInterfaceIp"
                  index: 2002
                - name: "hypervisorInterfaceIp"
                  index: 2003

    NsServiceEnum:
      description: DocRef(NsServiceNameDesc)
      allOf:
        - $ref: "ModelRef({ext:common:/namespaces/common/versioned/v1/modules/config/beta/models/BaseEnum})"
        - type: "string"
          enum:
            - DR
            - VOLUMES
            - BACKPLANE
            - RDMA
            - ISER
          x-constraints:
            maxLength: ConstantRef(maxNetworkSegmentServiceNameLength)
          x-codegen-hint:
            $any:
              - type: enum
                properties:
                  descriptions:
                    - name: "DR"
                      description: DocRef(NsDRDesc)
                    - name: "VOLUMES"
                      description: DocRef(NsVolumesDesc)
                    - name: "BACKPLANE"
                      description: DocRef(NsBackplaneDesc)
                    - name: "RDMA"
                      description: DocRef(NsRdmaDesc)
                    - name: "ISER"
                      description: DocRef(NsIserDesc)
              - type: entity-identifier
                properties:
                  identifiers:
                    - value: "DR"
                      index: 2001
                    - value: "VOLUMES"
                      index: 2002
                    - value: "BACKPLANE"
                      index: 2003
                    - value: "RDMA"
                      index: 2004
                    - value: "ISER"
                      index: 2005
          x-property-mapping:
            - name: DR
              value: 0
            - name: VOLUMES
              value: 1
            - name: BACKPLANE
              value: 2
            - name: RDMA
              value: 3
            - name: ISER
              value: 4
          x-type-mapping: int64

    NsServiceStateEnum:
      description: DocRef(NsServiceStatesDesc)
      allOf:
        - $ref: "ModelRef({ext:common:/namespaces/common/versioned/v1/modules/config/beta/models/BaseEnum})"
        - type: "string"
          enum:
            - INIT
            - CONFIGURED
            - FAILED
          x-codegen-hint:
            $any:
              - type: enum
                properties:
                  descriptions:
                    - name: "INIT"
                      description: DocRef(NsServiceInitDesc)
                    - name: "CONFIGURED"
                      description: DocRef(NsServiceConfiguredDesc)
                    - name: "FAILED"
                      description: DocRef(NsServiceFailedDesc)
              - type: entity-identifier
                properties:
                  identifiers:
                    - value: "INIT"
                      index: 2001
                    - value: "CONFIGURED"
                      index: 2002
                    - value: "FAILED"
                      index: 2003

    NsBackingType:
      description: DocRef(NsBackingTypeDesc)
      allOf:
        - $ref: "ModelRef({ext:common:/namespaces/common/versioned/v1/modules/config/beta/models/BaseEnum})"
        - type: "string"
          enum:
            - ESX_VSS
            - ESX_DVS
            - AHV_VS
            - AHV_BRIDGE
          x-codegen-hint:
            $any:
              - type: enum
                properties:
                  descriptions:
                    - name: "ESX_VSS"
                      description: DocRef(NsBackingEsxVssDesc)
                    - name: "ESX_DVS"
                      description: DocRef(NsBackingEsxDvsDesc)
                    - name: "AHV_VS"
                      description: DocRef(NsBackingAhvVsDesc)
                    - name: "AHV_BRIDGE"
                      description: DocRef(NsBackingAhvBridgeDesc)
              - type: entity-identifier
                properties:
                  identifiers:
                    - value: "ESX_VSS"
                      index: 2001
                    - value: "ESX_DVS"
                      index: 2002
                    - value: "AHV_VS"
                      index: 2003
                    - value: "AHV_BRIDGE"
                      index: 2004

    NsIpPoolType:
      description: DocRef(NsIpPoolTypeDesc)
      allOf:
        - $ref: "ModelRef({ext:common:/namespaces/common/versioned/v1/modules/config/beta/models/BaseEnum})"
        - type: "string"
          enum:
            - PE_IP_POOL
          x-codegen-hint:
            $any:
              - type: enum
                properties:
                  descriptions:
                    - name: "PE_IP_POOL"
                      description: DocRef(NsPeIpPoolDesc)
              - type: entity-identifier
                properties:
                  identifiers:
                    - value: "PE_IP_POOL"
                      index: 2001

    NetworkSegmentService:
      description: DocRef(NetworkSegmentServiceDesc)
      type: "object"
      properties:
        name:
          description: DocRef(NsServiceNameDesc)
          $ref: ModelRef({./NsServiceEnum})
        isDisabled:
          description: DocRef(NsServiceIsDisabledDesc)
          type: "boolean"
          default: false
        state:
          description: DocRef(NsServicestatesDesc)
          $ref: ModelRef({./NsServiceStateEnum})
        clientSubnets:
          description: DocRef(NsClientSubnetsDesc)
          type: array
          minItems: 0
          maxItems: 64
          items:
            $ref: ModelRef({ext:common:/namespaces/common/versioned/v1/modules/config/beta/models/IPAddress})
        virtualIpAddress:
          description: DocRef(NsVirtualIpAddressDesc)
          $ref: ModelRef({ext:common:/namespaces/common/versioned/v1/modules/config/beta/models/IPAddress})
      x-complex-type-edm: true
      x-filterable-properties:
        - name
      x-property-mapping:
        - name: "name"
          value: "service_name"
      x-internal: true
      x-codegen-hint:
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: "name"
                  index: 2001
                - name: "isDisabled"
                  index: 2002
                - name: "state"
                  index: 2003
                - name: "clientSubnets"
                  index: 2004
                - name: "virtualIpAddress"
                  index: 2005

    NetworkSegmentNetworkBacking:
      description: DocRef(NetworkSegmentNetworkBackingDesc)
      type: "object"
      properties:
        hypervisorType:
          description: DocRef(HypervisorTypes)
          $ref: ModelRef({./HypervisorType})
        cvmInterfaceBacking:
          description: DocRef(NsCvmInterfaceBackingDesc)
          type: "string"
          x-constraints:
            maxLength: ConstantRef(maxInterfaceBackingLength)
        hypervisorInterfaceBacking:
          description: DocRef(NsHypervisorInterfaceBackingDesc)
          type: "string"
          x-constraints:
            maxLength: ConstantRef(maxInterfaceBackingLength)
        backingType:
          description: DocRef(NsBackingTypeDesc)
          $ref: ModelRef({./NsBackingType})
      x-internal: true
      x-codegen-hint:
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: "hypervisorType"
                  index: 2001
                - name: "cvmInterfaceBacking"
                  index: 2002
                - name: "hypervisorInterfaceBacking"
                  index: 2003
                - name: "backingType"
                  index: 2004
