components:
  schemas:
    StorageSummary:
      x-property-mapping:
        - name: "clusterFaultTolerantCapacity"
          value: "cluster_fault_tolerant_capacity"
      x-entity: storage_summary
      type: "object"
      description: DocRef(StorageSummaryEntityDesc)
      properties:
            clusterFaultTolerantCapacity:
              description: DocRef(ClusterFaultTolerantCapacityDesc)
              type: "integer"
              format: int32
              readOnly: true
      x-codegen-hint:
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: "clusterFaultTolerantCapacity"
                  index: 2001