paths:
  /domain-managers/{extId}/$actions/configure-connection:
    post:
      tags:
        - "ApiEndpoint(DomainManager)"
      summary: DocRef(ConfigureConnectionSummary)
      description: DocRef(ConfigureConnectionDescription)
      operationId: configureConnection
      x-internal-api: true
      x-supported-versions:
        - product: PC
          version: 2024.3
      requestBody:
        description: DocRef(ConnectionConfigSpec)
        content:
          application/json:
            schema:
              $ref: "ModelRef({/namespaces/prism/versioned/v4/modules/management/beta/models/ConnectionConfigurationSpec})"
        required: true
      parameters:
        - name: extId
          in: path
          description: DocRef(ExtIdDescription)
          required: true
          schema:
            type: string
            x-constraints:
              pattern: "ConstantRef({ext:common:/namespaces/common}, uuidPattern)"
      x-permissions:
        displayName: Configure a Domain Manager connection (Register domain manager)
        entityType: prism_central
        operationName: Configure_Domain_Manager_Connection
        serviceName: Prism
        roleList:
          - Super Admin
          - Internal Super Admin
          - Prism Admin
          - Cluster Admin
          - Domain Manager Admin
      x-codegen-hint:
        spring-mvc:
          - type: non-blocking
            properties:
              non-blocking: true
          - type: rbac
            properties:
              metadataProvider: com.nutanix.prism.rbac.metadata.provider.AllowAllMetadataProvider
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: "extId"
                  index: 2001
                - name: "body"
                  index: 2002
      x-rate-limit:
        type: pc
        config:
          - type: xsmall
            count: 1
            timeUnit: seconds
          - type: small
            count: 2
            timeUnit: seconds
          - type: large
            count: 3
            timeUnit: seconds
          - type: xlarge
            count: 5
            timeUnit: seconds
      x-required-headers:
        - name: NTNX-Request-Id
          description: DocRef({ext:common:/namespaces/common}, requestIdHeaderDesc)
        - name: If-Match
          description: DocRef({ext:common:/namespaces/common}, ifMatchHeaderDesc)
      responses:
        202:
          description: DocRef({ext:common:/namespaces/common}, 202AcceptedDesc)
          content:
            application/json:
              schema:
                $ref: "ModelRef({ext:tasks:/namespaces/prism/versioned/v4/modules/config/beta/models/TaskReference})"
        x-api-responses:
          template: "ext:common:/namespaces/common/versioned/v1/modules/response/beta/models/apiResponse"
          responseModelName: "ConfigureConnectionApiResponse"
        x-codegen-hint:
          $any:
            - type: entity-identifier
              properties:
                identifiers:
                  - type: "ModelRef({ext:tasks:/namespaces/prism/versioned/v4/modules/config/beta/models/TaskReference})"
                    index: 2001

  /domain-managers/{extId}/$actions/unconfigure-connection:
    post:
      tags:
        - "ApiEndpoint(DomainManager)"
      summary: DocRef(UnconfigureConnectionSummary)
      description: DocRef(UnconfigureConnectionDescription)
      operationId: unconfigureConnection
      x-internal-api: true
      x-supported-versions:
        - product: PC
          version: 2024.3
      requestBody:
        description: DocRef(UnconfigureConnectSpec)
        content:
          application/json:
            schema:
              $ref: "ModelRef({/namespaces/prism/versioned/v4/modules/management/beta/models/ConnectionUnconfigurationSpec})"
        required: true
      parameters:
        - name: extId
          in: path
          description: DocRef(ExtIdDescription)
          required: true
          schema:
            type: string
            x-constraints:
              pattern: "ConstantRef({ext:common:/namespaces/common}, uuidPattern)"
      x-permissions:
        displayName: Unconfigure connection to a Domain Manager
        entityType: prism_central
        operationName: Unconfigure_Domain_Manager_Connection
        serviceName: Prism
        roleList:
          - Super Admin
          - Internal Super Admin
          - Prism Admin
          - Cluster Admin
          - Domain Manager Admin
      x-codegen-hint:
        spring-mvc:
          - type: non-blocking
            properties:
              non-blocking: true
          - type: rbac
            properties:
              metadataProvider: com.nutanix.prism.rbac.metadata.provider.AllowAllMetadataProvider
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: "extId"
                  index: 2001
                - name: "body"
                  index: 2002
      x-rate-limit:
        type: pc
        config:
          - type: xsmall
            count: 1
            timeUnit: seconds
          - type: small
            count: 2
            timeUnit: seconds
          - type: large
            count: 3
            timeUnit: seconds
          - type: xlarge
            count: 5
            timeUnit: seconds
      x-required-headers:
        - name: NTNX-Request-Id
          description: DocRef({ext:common:/namespaces/common}, requestIdHeaderDesc)
        - name: If-Match
          description: DocRef({ext:common:/namespaces/common}, ifMatchHeaderDesc)
      responses:
        202:
          description: DocRef({ext:common:/namespaces/common}, 202AcceptedDesc)
          content:
            application/json:
              schema:
                $ref: "ModelRef({ext:tasks:/namespaces/prism/versioned/v4/modules/config/beta/models/TaskReference})"
        x-api-responses:
          template: "ext:common:/namespaces/common/versioned/v1/modules/response/beta/models/apiResponse"
          responseModelName: "UnconfigureConnectionApiResponse"
        x-codegen-hint:
          $any:
            - type: entity-identifier
              properties:
                identifiers:
                  - type: "ModelRef({ext:tasks:/namespaces/prism/versioned/v4/modules/config/beta/models/TaskReference})"
                    index: 2001
