paths:
  /clusters/{clusterExtId}/network-segments/{extId}:
    x-backend-service-name: mitra
    get:
      tags:
        - "ApiEndpoint(Network Segments)"
      description: DocRef(GetNetworkSegmentDesc)
      summary: DocRef(GetNetworkSegmentSummaryDesc)
      operationId: "getNetworkSegmentById"
      x-internal-api: true
      x-supported-versions:
        - product: PC
          version: 2024.3
        - product: PE
          version: 6.9
      x-permissions:
        operationName: Get_Cluster_Network_Segment
        serviceName: Clustermgmt
        entityType: cluster
        isListCall: false
        deploymentList:
          - ON_PREM
        roleList:
          - Cluster Admin
          - Cluster Viewer
          - Internal Super Admin
          - Prism Admin
          - Prism Viewer
          - Self-Service Admin
          - Super Admin
      x-codegen-hint:
        spring-mvc:
          - type: "non-blocking"
            properties:
              non-blocking: true
          - type: "rbac"
            properties:
              basedInIDF: true
              metadataProvider: com.nutanix.clustermgmtserver.rbac.metadata.provider.ClusterEntitySpecificMetadataProvider
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: "clusterExtId"
                  index: 2001
                - name: "extId"
                  index: 2002
      parameters:
        - name: clusterExtId
          in: path
          description: DocRef(ClusterExtIdDescription)
          required: true
          schema:
            type: string
            x-constraints:
              pattern: "ConstantRef({ext:common:/namespaces/common}, uuidPattern)"
        - name: extId
          in: path
          description: DocRef(NetworkSegmentExtIdDesc)
          required: true
          schema:
            type: string
            x-constraints:
              pattern: "ConstantRef({ext:common:/namespaces/common}, uuidPattern)"
      responses:
        200:
          description: DocRef(GetNetworkSegmentResponseDesc)
          content:
            application/json:
              schema:
                $ref: ModelRef({/namespaces/clustermgmt/versioned/v4/modules/config/beta/models/NetworkSegment})
        x-api-responses:
          responseModelName: "GetNetworkSegmentApiResponse"
          template: ext:common:/namespaces/common/versioned/v1/modules/response/beta/models/apiResponse
        x-codegen-hint:
          $any:
            - type: entity-identifier
              properties:
                identifiers:
                  - type: "ModelRef({/namespaces/clustermgmt/versioned/v4/modules/config/beta/models/NetworkSegment})"
                    index: 2001
      x-documentation-tag: Clusters

  /clusters/{clusterExtId}/network-segments:
    x-backend-service-name: mitra
    get:
      tags:
        - "ApiEndpoint(Network Segments)"
      description: DocRef(GetNetworkSegmentsDesc)
      summary: DocRef(GetNetworkSegmentsSummaryDesc)
      operationId: "listNetworkSegmentsByClusterId"
      x-internal-api: true
      x-supported-versions:
        - product: PC
          version: 2024.3
        - product: PE
          version: 6.9
      x-permissions:
        operationName: Get_Cluster_Network_Segment
        serviceName: Clustermgmt
        entityType: cluster
        isListCall: true
        deploymentList:
          - ON_PREM
        roleList:
          - Cluster Admin
          - Cluster Viewer
          - Internal Super Admin
          - Prism Admin
          - Prism Viewer
          - Self-Service Admin
          - Super Admin
      x-codegen-hint:
        spring-mvc:
          - type: "non-blocking"
            properties:
              non-blocking: true
          - type: "rbac"
            properties:
              basedInIDF: true
              metadataProvider: com.nutanix.clustermgmtserver.rbac.metadata.provider.ClusterEntitySpecificMetadataProvider
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: "clusterExtId"
                  index: 2001
                - name: "$page"
                  index: 2002
                - name: "$limit"
                  index: 2003
                - name: "$filter"
                  index: 2004
                - name: "$orderby"
                  index: 2005
      parameters:
        - name: clusterExtId
          in: path
          description: DocRef(ClusterExtIdDescription)
          required: true
          schema:
            type: string
            x-constraints:
              pattern: "ConstantRef({ext:common:/namespaces/common}, uuidPattern)"
      x-api-features:
        - ApiFeature(PARAMETERS, {ext:common:/namespaces/common/versioned/v1/modules/config/beta/models/Page})
      responses:
        200:
          description: DocRef(GetNetworkSegmentsResponseDesc)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ModelRef({/namespaces/clustermgmt/versioned/v4/modules/config/beta/models/NetworkSegment})
        x-api-responses:
          responseModelName: "ListNetworkSegmentsByClusterIdApiResponse"
          template: ext:common:/namespaces/common/versioned/v1/modules/response/beta/models/apiResponse
        x-codegen-hint:
          $any:
            - type: entity-identifier
              properties:
                identifiers:
                  - type: "ModelRef({/namespaces/clustermgmt/versioned/v4/modules/config/beta/models/NetworkSegment})"
                    container: "array"
                    index: 2001
      x-documentation-tag: Clusters
      x-support-projection: true