components:
  schemas:
    BootDeviceDisk:
      description: DocRef(BootDeviceDiskDescription)
      type: object
      properties:
        diskAddress:
          $ref: "ModelRef({./DiskAddress})"
      x-codegen-hint:
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: diskAddress
                  index: 2001
    BootDeviceNic:
      description: DocRef(BootDeviceNicDescription)
      type: object
      properties:
        macAddress:
          description: DocRef(BootDeviceNicMacAddressDescription)
          type: string
          x-constraints:
            pattern: "ConstantRef({ext:common:/namespaces/common}, macPattern)"
      x-codegen-hint:
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: macAddress
                  index: 2001
    BootDeviceType:
      # Note: If new BootDeviceType is added or the exising one is removed, please update the corresponding maxItems in
      # LegacyBoot| bootOrder
      description: DocRef(BootDeviceType)
      allOf:
        - $ref: "ModelRef({ext:common:/namespaces/common/versioned/v1/modules/config/beta/models/BaseEnum})"
        - type: string
          enum:
            - CDROM
            - DISK
            - NETWORK
      x-codegen-hint:
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - value: CDROM
                  index: 2001
                - value: DISK
                  index: 2002
                - value: NETWORK
                  index: 2003
          - type: enum
            properties:
              descriptions:
                - name: CDROM
                  description: DocRef(CdRomBootDeviceTypeDescription)
                - name: DISK
                  description: DocRef(DiskBootDeviceTypeDescription)
                - name: NETWORK
                  description: DocRef(NicBootDeviceTypeDescription)
    LegacyBoot:
      type: object
      description: DocRef(LegacyBootDescription)
      properties:
        bootDevice:
          description: DocRef(LegacyBootDeviceDescription)
          oneOf:
            - $ref: "ModelRef({./BootDeviceDisk})"
            - $ref: "ModelRef({./BootDeviceNic})"
          x-codegen-hint:
            $any:
              - type: entity-identifier
                properties:
                  identifiers:
                    - type: "ModelRef({./BootDeviceDisk})"
                      index: 2001
                    - type: "ModelRef({./BootDeviceNic})"
                      index: 2002
        bootOrder:
          description: DocRef(BootDeviceOrderDescription)
          type: array
          minItems: 0
          maxItems: 3
          items:
            $ref: "ModelRef({./BootDeviceType})"
          uniqueItems: true
      x-codegen-hint:
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: bootOrder
                  index: 2003
    NvramDevice:
      type: object
      description: DocRef(NvramDescription)
      properties:
        backingStorageInfo:
          $ref: "ModelRef({./VmDisk})"
      x-codegen-hint:
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: backingStorageInfo
                  index: 2001
    UefiBoot:
      type: object
      description: DocRef(UefiBootDescription)
      properties:
        isSecureBootEnabled:
          description: DocRef(UefiBootSecureBootEnabledDescription)
          type: boolean
        nvramDevice:
          description: DocRef(UefiBootNvramDeviceDescription)
          readOnly: true
          $ref: "ModelRef({./NvramDevice})"
      x-codegen-hint:
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: type
                  index: 2001
                - name: isSecureBootEnabled
                  index: 2002
                - name: nvramDevice
                  index: 2003
