components:
  schemas:
    ConnectionConfigurationSpec:
      type: "object"
      description: DocRef(ConnectionConfigSpec)
      required:
        - remoteCluster
      properties:
        remoteCluster:
          description: DocRef(RemoteClusterDetailsDescription)
          $ref: "ModelRef({./RemoteCluster})"
      x-codegen-hint:
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: remoteCluster
                  index: 2001
    ConnectionUnconfigurationSpec:
      type: "object"
      description: DocRef(UnconfigureConnectSpec)
      required:
        - remoteCluster
      properties:
        remoteCluster:
          description: DocRef(RemoteClusterDetailsDescription)
          $ref: "ModelRef({./ClusterReference})"
      x-codegen-hint:
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: remoteCluster
                  index: 3001

    RemoteCluster:
      description: DocRef(RemoteClusterDetailsDescription)
      allOf:
        - $ref: "ModelRef({ext:common:/namespaces/common/versioned/v1/modules/response/beta/models/ExternalizableAbstractModel})"
        - type: object
          required:
            - extId
            - externalAddress
          properties:
            name:
              description: DocRef(RemoteClusterNameDescription)
              type: string
              x-constraints:
                minLength: ConstantRef(minClusterNameLength)
                maxLength: ConstantRef(maxClusterNameLength)
            externalAddress:
              description: DocRef(ExternalAddressDescription)
              $ref: ModelRef({ext:common:/namespaces/common/versioned/v1/modules/config/beta/models/IPAddressOrFQDN})
            nodeIpAddresses:
              description: DocRef(NodeIpAddressesDescription)
              type: array
              items:
                $ref: ModelRef({ext:common:/namespaces/common/versioned/v1/modules/config/beta/models/IPAddressOrFQDN})
              x-constraints:
                minItems: ConstantRef(ClusterMinNodeCount)
                maxItems: ConstantRef(ClusterMaxNodeCount)
      x-codegen-hint:
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - type: "ModelRef({ext:common:/namespaces/common/versioned/v1/modules/response/beta/models/ExternalizableAbstractModel})"
                  name: base
                  index: 4001
                - name: type
                  index: 4002
                - name: name
                  index: 4003
                - name: externalAddress
                  index: 4004
                - name: port
                  index: 4005
                - name: nodeIpAddresses
                  index: 4006