paths:
  /tasks/{extId}:
    get:
      tags:
        - "ApiEndpoint(Tasks)"
      summary: DocRef(TaskGetSummary)
      description: DocRef(TaskGetDescription)
      operationId: "getTaskById"
      x-supported-versions:
        - product: PC
          version: 2024.1
      x-permissions:
        operationName: View_Task
        description: DocRef(ViewTaskPermissionDescription)
        serviceName: Prism
        entityType: task
        deploymentList:
          - ON_PREM
          - CLOUD
        roleList:
          - Internal Super Admin
          - Prism Admin
          - Self-Service Admin
          - Super Admin
          - Prism Viewer
          - Task Self Owned
          - CSI System
          - Kubernetes Data Services System
          - Administrator
          - Account Owner
          - Monitoring Admin
      x-rate-limit:
        type: pc
        config:
          - type: xsmall
            count: 27
            timeUnit: seconds
          - type: Small
            count: 36
            timeUnit: seconds
          - type: Large
            count: 54
            timeUnit: seconds
          - type: XLarge
            count: 72
            timeUnit: seconds
      parameters:
        - name: extId
          in: path
          description: DocRef(TaskExtIdParamDescription)
          required: true
          schema:
            type: string
            x-constraints:
              pattern: ConstantRef(taskExtIdPattern)
      x-codegen-hint:
        spring-mvc:
          - type: non-blocking
            properties:
              non-blocking: true
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: "extId"
                  index: 2001
      responses:
        200:
          description: DocRef(TaskGetSuccess)
          content:
            application/json:
              schema:
                $ref: ModelRef({/namespaces/prism/versioned/v4/modules/config/beta/models/Task})
        x-api-responses:
          template: "ext:common:/namespaces/common/versioned/v1/modules/response/beta/models/apiResponse"
          responseModelName: GetTaskApiResponse
        x-codegen-hint:
          $any:
            - type: entity-identifier
              properties:
                identifiers:
                  - type: ModelRef({/namespaces/prism/versioned/v4/modules/config/beta/models/Task})
                    index: 2001
      x-support-projection: true

  /tasks/{taskExtId}/$actions/cancel:
    post:
      tags:
        - "ApiEndpoint(Tasks)"
      summary: DocRef(TaskCancelSummary)
      description: DocRef(TaskCancelDescription)
      operationId: "cancelTask"
      x-supported-versions:
        - product: PC
          version: 2024.1
      x-permissions:
        operationName: Cancel_Task
        description: DocRef(CancelTaskPermissionDescription)
        serviceName: Prism
        entityType: task
        deploymentList:
          - ON_PREM
          - CLOUD
        roleList:
          - Internal Super Admin
          - Prism Admin
          - Self-Service Admin
          - Super Admin
      x-rate-limit:
        type: pc
        config:
          - type: xsmall
            count: 10
            timeUnit: seconds
          - type: Small
            count: 20
            timeUnit: seconds
          - type: Large
            count: 20
            timeUnit: seconds
          - type: XLarge
            count: 20
            timeUnit: seconds
      parameters:
        - name: taskExtId
          in: path
          description: DocRef(TaskExtIdParamDescription)
          required: true
          schema:
            type: string
            x-constraints:
              pattern: ConstantRef(taskExtIdPattern)
      x-codegen-hint:
        spring-mvc:
          - type: non-blocking
            properties:
              non-blocking: true
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: "taskExtId"
                  index: 2001
      responses:
        200:
          description: DocRef(TaskCancelSuccess)
          content:
            application/json:
              schema:
                $ref: "ModelRef({/namespaces/prism/versioned/v4/modules/error/beta/models/AppMessage})"
        x-api-responses:
          template: "ext:common:/namespaces/common/versioned/v1/modules/response/beta/models/apiResponse"
          responseModelName: CancelTaskApiResponse
        x-codegen-hint:
            $any:
              - type: entity-identifier
                properties:
                  identifiers:
                    - type: "ModelRef({/namespaces/prism/versioned/v4/modules/error/beta/models/AppMessage})"
                      index: 2001

  /tasks:
    get:
      tags:
        - "ApiEndpoint(Tasks)"
      summary: DocRef(TaskListSummary)
      description: DocRef(TaskListDescription)
      operationId: "listTasks"
      x-supported-versions:
        - product: PC
          version: 2024.1
      x-permissions:
        operationName: View_Task
        description: DocRef(ViewTaskPermissionDescription)
        serviceName: Prism
        entityType: task
        deploymentList:
          - ON_PREM
          - CLOUD
        roleList:
          - Internal Super Admin
          - Prism Admin
          - Self-Service Admin
          - Super Admin
          - Prism Viewer
          - Task Self Owned
          - CSI System
          - Kubernetes Data Services System
          - Administrator
          - Account Owner
          - Monitoring Admin
      x-rate-limit:
        type: pc
        config:
          - type: xsmall
            count: 6
            timeUnit: seconds
          - type: Small
            count: 6
            timeUnit: seconds
          - type: Large
            count: 6
            timeUnit: seconds
          - type: XLarge
            count: 6
            timeUnit: seconds
      x-api-features:
        - ApiFeature(PARAMETERS, {ext:common:/namespaces/common/versioned/v1/modules/config/beta/models/Page})
      x-codegen-hint:
        spring-mvc:
          - type: non-blocking
            properties:
              non-blocking: true
        $any:
          - type: entity-identifier
            properties:
              identifiers:
                - name: "$page"
                  index: 2001
                - name: "$limit"
                  index: 2002
                - name: "$filter"
                  index: 2003
                - name: "$orderby"
                  index: 2004
      responses:
        200:
          description: DocRef(TaskListSuccess)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ModelRef({/namespaces/prism/versioned/v4/modules/config/beta/models/Task})
        x-api-responses:
          template: "ext:common:/namespaces/common/versioned/v1/modules/response/beta/models/apiResponse"
          responseModelName: ListTasksApiResponse
        x-codegen-hint:
          $any:
            - type: entity-identifier
              properties:
                identifiers:
                  - type: ModelRef({/namespaces/prism/versioned/v4/modules/config/beta/models/Task})
                    container: "array"
                    index: 2001
      x-support-projection: true
